services:
  db:
    container_name: db
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  site:
    container_name: site-1
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: notSecureChangeMe
    volumes:
      # Mount plugins and themes
      - wpcontent:/var/www/html/wp-content
      - ./html/wp-content/themes/mytheme:/var/www/html/wp-content/themes/mytheme
      - ./html/wp-content/plugins/myplugin:/var/www/html/wp-content/plugins/myplugin
  phpmyadmin:
    container_name: phpmyadmin-1
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

volumes:
  db:
  wpcontent:
